apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: car-rental-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: car-rental-frontend
spec:
  hosts:
  - "*"
  gateways:
  - car-rental-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: car-rental-frontend-service.default.svc.cluster.local
        subset: v1
      weight: 90
    - destination:
        host: car-rental-frontend-service.default.svc.cluster.local
        subset: v2
      weight: 10

